### ISSUE TITLE
Replace third party resources with custom resource definitions

### ISSUE THREAD

**Issue by ConnorDoyle** [Intel-Corp/CPU-Manager-for-Kubernetes#167]
TPRs have been deprecated in favor of CRDs (see https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/)

**Comment by flyingcougar** [comment]
#170

**Comment by Damenus** [comment]
#175  @flyingcougar  I've added unit test

**Comment by Damenus** [comment]
#176 I've added generated docs

**Comment by flyingcougar** [comment]
all done, closing
