### ISSUE TITLE
Why not implement cpuset in k8s?

### ISSUE THREAD

**Issue by hustcat** [Intel-Corp/CPU-Manager-for-Kubernetes#169]
Hi guys, k8s community has discuss [cpuset isolation](https://github.com/kubernetes/kubernetes/issues/10570) long ago. Why not implement cpuset  directly in k8s?

**Comment by flyingcougar** [comment]
@hustcat Here are some links:
 - [Proposal](https://github.com/kubernetes/community/pull/654)
 - [Code](https://github.com/kubernetes/kubernetes/pull/49186)

CPU Manager work in k8s is WIP (hopefully 1.8), we needed a solution for cpu isolation way faster.
